[data-sources]
boundary-lines-110m = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip"
boundary-lines-50m  = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_boundary_lines_land.zip"
boundary-lines-10m  = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_boundary_lines_land.zip"
state-lines-50m     = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces_lines.zip"
state-lines-10m     = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip"
glaciers-110m       = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_glaciated_areas.zip"

[data-store]
hosts = [
    "http://172.17.0.2:9200"
]
